language: node_js
node_js:
  - 13

services:
  - docker

#Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print teh version for logging
  - docker build -t simple-node-t .
  - docker tag simple-node-t geedino07/simple-node .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push geedino07/simple-node


